# -*- coding: utf-8 -*-
"""uber_example.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxZB42Pp2kMrN8dJ7zRv_5rXgpzKSQMg
"""

import streamlit as st
import pandas as pd
import numpy as np

st.title("uber pickups in NYC")

DATA_COLUMN = "data/time"
DATA_url = ("https://s3-us-west-2.amazonaws.com/"
            "streamlit-demo-data/uber-raw-data-sep14.csv.gz")
@st.cache_data
def load_data(nrows):
    data = pd.read_csv(DATA_url, nrows=nrows)
    lowercase = lambda x: str(x).lower()
    data.rename(lowercase, axis="columns", inplace=True)
    data[DATA_COLUMN] = pd.to_datetime(data[DATA_COLUMN])
    return data

data_load_state = st.text("loading data...")
data = load_data(10000)
data_load_state.text("done! (using st.cache_data)")

if st.checkbox("show raw data"):
    st.subheader("raw data")
    st.write(data)

st.subheader("number of pickups by hour")
hist_values = np.histogram(data[DATA_COLUMN].dt.hour, bins=24, range=(0,24))[0]
st.bar_chart(hist_values)

#somo number in the range 0, 23
hour_to_filter = st.slider("hour", 0, 23, 17)
filtered_data = data[data[DATA_COLUMN].dt.hour == hour_to_filter]

st.subheader(f"map of all pickups at {hour_to_filter}:00")
st.map(filtered_data)

